### ISSUE TITLE
node-red-node-ui-table/node.js:48:30: MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by gitjps** [node-red/node-red-ui-nodes#25]
### Which node are you reporting an issue on?
node-ui-table

### What are the steps to reproduce?
1) I created this flow (node-ui-table & slider)
```
[{"id":"ee5a7b28.ac0fa8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"668c217.ea598e","type":"inject","z":"ee5a7b28.ac0fa8","name":"","topic":"","payload":"[{\"Name\":\"Kazuhito Yokoi\",\"Age\":\"35\",\"Favourite Color\":\"red\",\"Date Of Birth\":\"12/09/1983\"},{\"Name\":\"Oli Bob\",\"Age\":\"12\",\"Favourite Color\":\"red\",\"Date Of Birth\":\"12/08/2017\"}]","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":230,"y":260,"wires":[["9f5f20ff.45c47"]]},{"id":"9f5f20ff.45c47","type":"ui_table","z":"ee5a7b28.ac0fa8","group":"3a4ba8c1.c6cfb8","name":"","order":3,"width":0,"height":4,"columns":[],"outputs":0,"cts":false,"x":430,"y":260,"wires":[]},{"id":"4ef5afb0.350e4","type":"comment","z":"ee5a7b28.ac0fa8","name":"Normal table","info":"","x":230,"y":220,"wires":[]},{"id":"b3d28479.ad8f28","type":"ui_slider","z":"ee5a7b28.ac0fa8","name":"","label":"slider","tooltip":"","group":"3a4ba8c1.c6cfb8","order":1,"width":0,"height":0,"passthru":true,"outs":"all","topic":"","min":0,"max":10,"step":1,"x":420,"y":320,"wires":[[]]},{"id":"3a4ba8c1.c6cfb8","type":"ui_group","z":"ee5a7b28.ac0fa8","name":"Default","tab":"79971fbf.fa897","order":1,"disp":true,"width":"6","collapse":false},{"id":"79971fbf.fa897","type":"ui_tab","z":"ee5a7b28.ac0fa8","name":"Home","icon":"track_changes","order":1,"disabled":false,"hidden":false}]
```

2) clicked on the inject node

### What happens?
I can see the slider but not the table (maybe I missed something)
log:
```
Starting flows
{ Error: Cannot find module 'node-red-dashboard'
    at Object.requireModule [as require] (/usr/src/node-red/node_modules/@node-red/registry/lib/util.js:48:19)
    at new TableNode (/data/node_modules/node-red-node-ui-table/node.js:48:30)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:189:48)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
    at stop.then.then (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:196:21)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

```
### What do you expect to happen?
a table appearing on the dashboard

### Please tell us about your environment:

- [ ] Node-RED version: v1.0.3
- [ ] node.js version:v10.19.0
- [ ] npm version: installed via Docker
- [ ] Platform/OS: macOS
- [ ] Browser: Chrome

**Comment by dceejay** [comment]
Hi which version of dashboard do you have installed ?

**Comment by gitjps** [comment]
node-red-dashboard, version: 2.19.3

**Comment by dceejay** [comment]
odd - I get
![image](https://user-images.githubusercontent.com/5375409/74060831-b10bd280-49e2-11ea-9e15-7cc7c325d094.png)

Have you restarted Node-RED since installing the table node ?

**Comment by gitjps** [comment]
thx for this advise, I killed the Node-RED container and restarted it with `docker start <container>`
