### ISSUE TITLE
Table gives error installing en freezes dashboard use

### ISSUE THREAD

**Issue by mariowitdoek** [node-red/node-red-ui-nodes#31]
I tried the node-red-node-ui-table but even the simple example does not work. On top the current UI layout did not accept any more other and the hamburger button was not visible any more. I do not know if these last events have anything to do with it but I give it as background info.
When looking at the install log after uninstalling and reinstalling I noticed an error message:
 TypeError: ui.getSizes is not a function
    at new TableNode (C:\Users\SalesTV\.node-red\node_modules\node-red-node-ui-table\node.js:49:32)
    at Object.createNode (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:190:48)
    at start (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:345:33)
    at C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:212:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

The whole log was:

6 Mar 12:28:07 - [info]

Welcome to Node-RED
===================

6 Mar 12:28:07 - [info] Node-RED version: v1.0.4
6 Mar 12:28:07 - [info] Node.js  version: v12.16.1
6 Mar 12:28:07 - [info] Windows_NT 10.0.18362 x64 LE
6 Mar 12:28:07 - [info] Loading palette nodes
6 Mar 12:28:09 - [info] +-----------------------------------------------------
6 Mar 12:28:09 - [info] | uibuilder initialised:
6 Mar 12:28:09 - [info] |   root folder: \Users\SalesTV\.node-red\uibuilder
6 Mar 12:28:09 - [info] |   version . .: 2.0.7
6 Mar 12:28:09 - [info] |   packages . : vue,bootstrap,bootstrap-vue,socket.io
6 Mar 12:28:09 - [info] +-----------------------------------------------------
6 Mar 12:28:09 - [info] Dashboard version 2.13.0 started at /ui
6 Mar 12:28:09 - [warn] ------------------------------------------------------
6 Mar 12:28:09 - [warn] [node-red-contrib-mssql-plus/mssql] Type already registered
6 Mar 12:28:09 - [warn] ------------------------------------------------------
6 Mar 12:28:09 - [info] Settings file  : \Users\SalesTV\.node-red\settings.js
6 Mar 12:28:09 - [info] Context store  : 'default' [module=memory]
6 Mar 12:28:09 - [info] User directory : \Users\SalesTV\.node-red
6 Mar 12:28:09 - [warn] Projects disabled : editorTheme.projects.enabled=false
6 Mar 12:28:09 - [info] Flows file     : \Users\SalesTV\.node-red\flows_DESKTOP-A9EA1AA.json
6 Mar 12:28:09 - [info] Server now running at http://127.0.0.1:1880/
6 Mar 12:28:09 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

6 Mar 12:28:09 - [info] Starting flows
6 Mar 12:28:09 - [info] Started flows
6 Mar 12:29:01 - [info] Installing module: node-red-node-ui-table, version: 0.3.0
6 Mar 12:29:04 - [info] Installed module: node-red-node-ui-table
6 Mar 12:29:04 - [info] Added node types:
6 Mar 12:29:04 - [info]  - node-red-node-ui-table:ui_table
6 Mar 12:29:59 - [info] Stopping flows
6 Mar 12:29:59 - [info] Stopped flows
6 Mar 12:29:59 - [info] Starting flows
TypeError: ui.getSizes is not a function
    at new TableNode (C:\Users\SalesTV\.node-red\node_modules\node-red-node-ui-table\node.js:49:32)
    at Object.createNode (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:190:48)
    at start (C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:345:33)
    at C:\Users\SalesTV\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:212:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
6 Mar 12:29:59 - [info] Started flows

**Comment by dceejay** [comment]
I think you need a more recent version of node-red-dashboard as that function was added back in 2.16 I think (now 2.19.4)

**Comment by mariowitdoek** [comment]
Indeed, that solved the problem! TX & IOU

I did update Node.js and Node-Red but not the palettes. Sorry for this rookie mistake ...
