### ISSUE TITLE
node-red-ui-node-table  TypeError: ui.getTheme is not a function

### ISSUE THREAD

**Issue by peterprib** [node-red/node-red-ui-nodes#9]
### Which node are you reporting an issue on?
node-red-ui-node-table
### What are the steps to reproduce?
add table node
### What happens?
TypeError: ui.getTheme is not a function
    at new TableNode (C:\Users\nodered\.node-red\node_modules\node-red-ui-node-table\node.js:56:24)
    at Object.createNode (C:\Users\nodered\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\util.js:483:31)
    at Flow.start (C:\Users\nodered\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\Flow.js:176:44)
    at start (C:\Users\nodered\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\flows\index.js:329:33)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

and nothing appears in dashboard
### What do you expect to happen?
no  error message and table in dashboard
### Please tell us about your environment:
19 Aug 21:42:27 - [info] Node-RED version: v0.20.7
19 Aug 21:42:27 - [info] Node.js  version: v11.6.0
19 Aug 21:42:27 - [info] Windows_NT 10.0.14393 ia32 LE

- [ ] Node-RED version: v0.20.7
- [ ] node.js version:   v11.6.0
- [ ] npm version: 6.10.3
- [ ] Platform/OS: Windows_NT 10.0.14393 ia32 LE

- [ ] Browser: chrome

**Comment by dceejay** [comment]
which version of node-red-dashboard do you have installed ?

**Comment by peterprib** [comment]
2.14.0 have upgraded 2.16.0 and problem has gone

**Comment by dceejay** [comment]
thanks - but good spot.
